version: '3.8'

services:
  web:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port 5000
    networks:
      - app-network

  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
