"""SnapRecommendationScoreHistory table

Revision ID: 02a208d0bfa2
Revises: a195a38e9536
Create Date: 2025-01-27 11:55:40.641451

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02a208d0bfa2"
down_revision = "a195a38e9536"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snap_recommendation_score_history",
        sa.Column("snap_id", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("exclude", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category"], ["recommendation_category.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["snap_id"], ["snap.snap_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("snap_id", "category", "created_at"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snap_recommendation_score_history")
    # ### end Alembic commands ###
