"""Delete old scores

Revision ID: 065bdd8b72ae
Revises: 02a208d0bfa2
Create Date: 2025-01-27 12:26:22.339496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065bdd8b72ae'
down_revision = '02a208d0bfa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('snap_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('popularity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recency_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('trending_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['snap_id'], ['snap.snap_id'], name='scores_snap_id_fkey'),
    sa.PrimaryKeyConstraint('snap_id', name='scores_pkey')
    )
    # ### end Alembic commands ###
