"""Create RecommendationCategory and SnapCategoryScore, add exclude

Revision ID: 54528f756336
Revises: d58438ef9450
Create Date: 2025-01-24 07:20:26.589739

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54528f756336"
down_revision = "d58438ef9450"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_category",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "snap_recommendation_score",
        sa.Column("snap_id", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("exclude", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category"],
            ["recommendation_category.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snap_id"],
            ["snap.snap_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("snap_id", "category"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snap_recommendation_score")
    op.drop_table("recommendation_category")
    # ### end Alembic commands ###
