"""Add editorial snaps

Revision ID: 6d7d459e0721
Revises: 065bdd8b72ae
Create Date: 2025-02-07 10:31:00.712041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7d459e0721'
down_revision = '065bdd8b72ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial_slice',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editorial_slice_snap',
    sa.Column('editorial_slice_id', sa.String(), nullable=False),
    sa.Column('snap_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['editorial_slice_id'], ['editorial_slice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snap_id'], ['snap.snap_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('editorial_slice_id', 'snap_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('editorial_slice_snap')
    op.drop_table('editorial_slice')
    # ### end Alembic commands ###
