"""add date_published to snap

Revision ID: b6616f20474f
Revises: b2cb1a7be131
Create Date: 2026-06-15 12:00:49.971829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6616f20474f'
down_revision = 'b2cb1a7be131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_published', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snap', schema=None) as batch_op:
        batch_op.drop_column('date_published')

    # ### end Alembic commands ###
