"""Add ratings to snaps

Revision ID: c1096f7c4215
Revises: e25739667e4a
Create Date: 2025-08-27 11:45:33.836523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1096f7c4215'
down_revision = 'e25739667e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_votes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snap', schema=None) as batch_op:
        batch_op.drop_column('total_votes')
        batch_op.drop_column('raw_rating')

    # ### end Alembic commands ###
