"""add collector logs

Revision ID: e25739667e4a
Revises: 6d7d459e0721
Create Date: 2025-04-09 09:18:08.973172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25739667e4a'
down_revision = '6d7d459e0721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_step_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('step', sa.Enum('COLLECT', 'FILTER', 'EXTRA_FIELDS', 'SCORE', name='pipelinesteps'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_step_log')
    # ### end Alembic commands ###
