name: PR checks
on:
  pull_request:

jobs:
  run-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t snaprecommend .


      - name: Run container
        run: |
          docker run -d -p 80:80 --env-file .env snaprecommend
          sleep 5
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost

  
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            py:
              - '**/*.py'

      - name: Install Python dependencies
        if: ${{ steps.filter.outputs.py == 'true' }}
        run: |
          pip3 install -r requirements.txt
          pip3 install pytest

      - name: Run Python tests 
        if: ${{ steps.filter.outputs.py == 'true' }}
        run: |
          python3 -m pytest tests/
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            py:
              - '**/*.py'

      - uses: actions/setup-python@v5
        if: ${{ steps.filter.outputs.py == 'true' }}
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        if: ${{ steps.filter.outputs.py == 'true' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python
        if: ${{ steps.filter.outputs.py == 'true' }}
        run: flake8 --extend-ignore=E203,E501 --exclude generated snaprecommend collector

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            js:
              - '**/*.js'
            ts:
              - '**/*.ts'
            jsx:
              - '**/*.jsx'
            tsx:
              - '**/*.tsx'

      - name: Install JS dependencies
        if: ${{ steps.filter.outputs.js == 'true' || steps.filter.outputs.ts == 'true' || steps.filter.outputs.jsx == 'true' || steps.filter.outputs.tsx == 'true' }}
        run: yarn install --immutable
        working-directory: frontend

      - name: Lint JS
        if: ${{ steps.filter.outputs.js == 'true' || steps.filter.outputs.ts == 'true' || steps.filter.outputs.jsx == 'true' || steps.filter.outputs.tsx == 'true' }}
        run: yarn run eslint src
        working-directory: frontend

