"""add reaches_min_threshold col

Revision ID: 31f503fed09d
Revises: c075c55f05d3
Create Date: 2024-11-19 15:08:35.869849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f503fed09d'
down_revision: Union[str, None] = 'c075c55f05d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snap', sa.Column('reaches_min_threshold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snap', 'reaches_min_threshold')
    # ### end Alembic commands ###
